import type { WorkflowEnvironment, WorkflowJob } from '../workflowTypes';
import { artifactTargets, environmentTargets } from '../workflowArtifacts';
import { Field } from './ui';
import { WorkflowFiles } from './WorkflowFiles';

export function WorkflowJobEditor({ job, environments, onChange, onDelete, onReading }: { job: WorkflowJob; jobs: WorkflowJob[]; environments: WorkflowEnvironment[]; onChange: (value: Partial<WorkflowJob>) => void; onDelete: () => void; onReading: (delta: number) => void }) {

  return <section className="workflow-job" id={`editor-${job.id}`}><div className="workflow-job-row"><Field label={`${job.id} · 名称`}><input required maxLength={128} value={job.name} onChange={event => onChange({ name: event.target.value })} /></Field><div className="field"><span>目标环境</span><div className="choice-buttons" role="group" aria-label={`${job.id} · 目标环境`}>{environments.map(env => <button type="button" key={env.alias} aria-pressed={job.environment === env.alias} onClick={() => onChange({ environment: env.alias, node_aliases: undefined, artifacts: job.artifacts?.map(item => ({ ...item, targets: undefined, environment: undefined })) })}>{env.alias}</button>)}</div></div><Field label="NPU卡数"><input aria-label={`${job.id} · NPU 数量`} type="number" min={0} max={128} required value={job.npu_count} onChange={event => onChange({ npu_count: Number(event.target.value) })} /></Field><Field label="超时/分钟"><input aria-label={`${job.id} · 超时（分钟）`} type="number" min={1} max={10080} required value={job.timeout_seconds / 60} onChange={event => onChange({ timeout_seconds: Number(event.target.value) * 60 })} /></Field><button type="button" className="text-button danger-text" aria-label={`删除作业 ${job.id}`} onClick={onDelete}>删除</button></div><div className="choice-buttons job-kind" role="group" aria-label={`${job.id} · 执行方式`}><button type="button" aria-pressed={job.kind === 'batch'} onClick={() => onChange({ kind: 'batch' })}>运行后结束</button><button type="button" aria-pressed={job.kind === 'service'} onClick={() => onChange({ kind: 'service' })}>常驻服务</button></div>
    <WorkflowFiles label={`${job.id} 前校验`} steps={job.pre} onChange={pre => onChange({ pre })} onReading={onReading} /><WorkflowFiles label={`${job.id} 主执行`} steps={job.steps} onChange={steps => onChange({ steps })} onReading={onReading} />{job.kind === 'service' && <WorkflowFiles label={`${job.id} 就绪检查`} steps={job.ready} onChange={ready => onChange({ ready })} onReading={onReading} />}<WorkflowFiles label={`${job.id} 后确认`} steps={job.post} onChange={post => onChange({ post })} onReading={onReading} />{job.post.length > 0 && <div className="choice-buttons" role="group" aria-label={`${job.id} · 后确认策略`}><button type="button" aria-pressed={job.post_policy === 'success'} onClick={() => onChange({ post_policy: 'success' })}>成功后确认</button><button type="button" aria-pressed={job.post_policy === 'always'} onClick={() => onChange({ post_policy: 'always' })}>始终确认</button></div>}
    <section className="workflow-artifact-inputs"><div className="workflow-row-heading"><h5>产物归档</h5><button type="button" className="text-button" onClick={() => onChange({ artifacts: [...(job.artifacts || []), { path: '', label: '' }] })}>添加 {job.id} 产物</button></div>{job.artifacts?.map((artifact, index) => <div className="workflow-artifact-row" key={index}><div className="field"><span>服务器 - 容器（多选）</span><details className="artifact-target-picker"><summary><span>选择产物服务器与容器</span></summary><div className="artifact-target-options" role="group" aria-label={`${job.id} 产物 ${index + 1} · 目标容器与节点`}>{environmentTargets(environments).map(target => { const selected = artifactTargets(artifact, job, environments); const included = selected.some(item => item.environment === target.environment && item.node_alias === target.node_alias); return <label key={target.environment + '/' + target.node_alias}><input type="checkbox" checked={included} onChange={() => onChange({ artifacts: job.artifacts!.map((item, i) => i === index ? { ...item, environment: undefined, targets: included ? selected.filter(value => value.environment !== target.environment || value.node_alias !== target.node_alias) : [...selected, target] } : item) })} />{target.node_alias} - {target.environment}</label>; })}<button type="button" className="text-button" onClick={() => onChange({ artifacts: job.artifacts!.map((item,i) => i === index ? {...item,targets:undefined,environment:undefined} : item) })}>恢复当前作业全部节点</button></div></details><small>{artifactTargets(artifact, job, environments).map(target => `${target.node_alias} - ${target.environment}`).join('，') || '尚未选择目标'}</small></div><Field label={`${job.id} 产物 ${index + 1} · 名称`}><input required value={artifact.label} onChange={event => onChange({ artifacts: job.artifacts!.map((item, i) => i === index ? { ...item, label: event.target.value } : item) })} /></Field><Field label={`${job.id} 产物 ${index + 1} · 路径`} hint={'文件或目录均可归档。用 $HIVE_TASK_ID/$HIVE_JOB_ID 隔离输出，例如 /home/results/$HIVE_TASK_ID/$HIVE_JOB_ID'}><input aria-label={`${job.id} 产物 ${index + 1} · 路径`} required pattern="/.*" value={artifact.path} placeholder="/home/results/output.json" onChange={event => onChange({ artifacts: job.artifacts!.map((item, i) => i === index ? { ...item, path: event.target.value } : item) })} /></Field><button type="button" className="text-button" onClick={() => onChange({ artifacts: job.artifacts!.filter((_, i) => i !== index) })}>删除</button></div>)}</section>
  </section>;
}
