import { useState } from 'react';
import type { WorkflowEnvironment, WorkflowJob } from '../workflowTypes';
import { ErrorNotice, Field } from './ui';
import { WorkflowFiles } from './WorkflowFiles';
import { dependencyError } from './WorkflowGraph';

export function WorkflowJobEditor({ job, jobs, environments, onChange, onDelete, onReading }: { job: WorkflowJob; jobs: WorkflowJob[]; environments: WorkflowEnvironment[]; onChange: (value: Partial<WorkflowJob>) => void; onDelete: () => void; onReading: (delta: number) => void }) {
  const [error, setError] = useState('');
  const [ports, setPorts] = useState(job.ports.join(', '));
  return <section className="workflow-job"><div className="workflow-row-heading"><h4>{job.id}</h4><button type="button" className="text-button danger-text" onClick={onDelete}>删除作业</button></div><div className="form-grid"><Field label={`${job.id} · 名称`}><input required maxLength={128} value={job.name} onChange={event => onChange({ name: event.target.value })} /></Field><Field label={`${job.id} · 目标环境`}><select value={job.environment} onChange={event => onChange({ environment: event.target.value })}>{!environments.some(env => env.alias === job.environment) && <option>{job.environment}（引用已失效）</option>}{environments.map(env => <option key={env.alias} value={env.alias}>{env.alias} / {env.role} / {env.node_alias}</option>)}</select></Field><Field label={`${job.id} · 作业类型`}><select value={job.kind} onChange={event => onChange({ kind: event.target.value as WorkflowJob['kind'] })}><option value="batch">批处理，退出后完成</option><option value="service">常驻服务，就绪后供下游使用</option></select></Field><Field label={`${job.id} · NPU 数量`}><input type="number" min={0} max={128} required value={job.npu_count} onChange={event => onChange({ npu_count: Number(event.target.value) })} /></Field><Field label={`${job.id} · 超时（秒）`}><input type="number" min={1} max={604800} required value={job.timeout_seconds} onChange={event => onChange({ timeout_seconds: Number(event.target.value) })} /></Field><Field label={`${job.id} · 服务端口`}><input value={ports} placeholder="逗号分隔，例如 8000, 8001" onChange={event => { setPorts(event.target.value); const values = event.target.value.split(',').filter(value => value.trim()).map(Number); if (values.some(value => !Number.isInteger(value) || value < 1024 || value > 65535) || new Set(values).size !== values.length) event.target.setCustomValidity('端口需为 1024–65535 的不重复整数。'); else { event.target.setCustomValidity(''); onChange({ ports: values }); } }} /></Field></div>
    <div className="workflow-dependencies"><h5>前置依赖</h5>{jobs.filter(value => value.id !== job.id).map(previous => { const dependency = job.depends_on.find(item => item.job_id === previous.id); return <div className="workflow-dependency" key={previous.id}><label className="check-field simple"><input type="checkbox" checked={Boolean(dependency)} onChange={event => { const problem = event.target.checked ? dependencyError(jobs, previous.id, job.id) : ''; setError(problem); if (!problem) onChange({ depends_on: event.target.checked ? [...job.depends_on, { job_id: previous.id, condition: 'succeeded' }] : job.depends_on.filter(item => item.job_id !== previous.id) }); }} />{job.id} 依赖 {previous.id}</label>{dependency && <select aria-label={`${job.id} 等待 ${previous.id}`} value={dependency.condition} onChange={event => onChange({ depends_on: job.depends_on.map(item => item.job_id === previous.id ? { ...item, condition: event.target.value as 'succeeded' | 'ready' } : item) })}><option value="succeeded">执行成功</option>{previous.kind === 'service' && <option value="ready">服务就绪</option>}</select>}</div>; })}{jobs.length === 1 && <p className="muted small">添加其他作业后可设置依赖。</p>}<ErrorNotice text={error} /></div>
    <details><summary>前校验与后确认</summary><WorkflowFiles label={`${job.id} 前校验`} steps={job.pre} onChange={pre => onChange({ pre })} onReading={onReading} /><Field label={`${job.id} · 后确认策略`}><select value={job.post_policy} onChange={event => onChange({ post_policy: event.target.value as WorkflowJob['post_policy'] })}><option value="success">主执行成功后运行</option><option value="always">无论成功失败都运行</option></select></Field><WorkflowFiles label={`${job.id} 后确认`} steps={job.post} onChange={post => onChange({ post })} onReading={onReading} /></details>
    <WorkflowFiles label={`${job.id} 主执行`} steps={job.steps} onChange={steps => onChange({ steps })} onReading={onReading} />{job.kind === 'service' && <WorkflowFiles label={`${job.id} 就绪检查`} steps={job.ready} onChange={ready => onChange({ ready })} onReading={onReading} />}
    <section className="workflow-artifact-inputs"><div className="workflow-row-heading"><h5>产物归档</h5><button type="button" className="text-button" onClick={() => onChange({ artifacts: [...(job.artifacts || []), { path: '', label: '', kind: 'file' }] })}>添加 {job.id} 产物</button></div><p className="muted small">指定容器中的输出文件；metrics 类型由外部脚本导出通用 JSON，平台仅校验并展示。</p>{job.artifacts?.map((artifact, index) => <div className="workflow-step" key={index}><div className="form-grid"><Field label={`${job.id} 产物 ${index + 1} · 容器绝对路径`}><input required pattern="/.*" value={artifact.path} onChange={event => onChange({ artifacts: job.artifacts!.map((item, i) => i === index ? { ...item, path: event.target.value } : item) })} placeholder="/home/results/output.json" /></Field><Field label={`${job.id} 产物 ${index + 1} · 名称`}><input required value={artifact.label} onChange={event => onChange({ artifacts: job.artifacts!.map((item, i) => i === index ? { ...item, label: event.target.value } : item) })} /></Field><Field label={`${job.id} 产物 ${index + 1} · 类型`}><select value={artifact.kind} onChange={event => onChange({ artifacts: job.artifacts!.map((item, i) => i === index ? { ...item, kind: event.target.value as 'file' | 'metrics' } : item) })}><option value="file">原始文件</option><option value="metrics">通用指标 JSON</option></select></Field></div><button type="button" className="text-button" onClick={() => onChange({ artifacts: job.artifacts!.filter((_, i) => i !== index) })}>删除产物声明</button></div>)}</section>
  </section>;
}
