import type { WorkflowRun } from '../workflowTypes';
import { Badge } from './ui';

const text = (value: unknown): string => value == null ? '未提供' : typeof value === 'object' ? JSON.stringify(value) : String(value);
export function WorkflowEvidence({ workflowId, job }: { workflowId: string | number; job: WorkflowRun['jobs'][number] }) {
  const base = `/api/workflows/${encodeURIComponent(workflowId)}/jobs/${encodeURIComponent(job.id)}`;
  const verdict = job.metrics?.verdict;
  const verdictLabel = ['passed', 'pass'].includes(verdict || '') ? '外部判定：通过' : ['failed', 'fail'].includes(verdict || '') ? '外部判定：失败' : '业务判定未提供';
  return <div className="workflow-evidence">{job.cards && <p className="muted small">本作业 NPU：{job.cards.length ? job.cards.join(', ') : '不占用 NPU'}</p>}{job.attempts?.length ? <div className="table-scroll"><table className="evidence-table"><thead><tr><th>执行阶段</th><th>状态</th><th>退出码</th><th>日志完整性</th></tr></thead><tbody>{job.attempts.map((attempt, index) => <tr key={index}><td>{attempt.phase}</td><td><Badge value={attempt.status} label={attempt.status === 'SUCCEEDED' ? '执行成功' : undefined} /></td><td>{attempt.exit_code ?? '未返回'}</td><td>{attempt.log_truncated ? '存在截断标记' : '无截断标记'}</td></tr>)}</tbody></table></div> : null}
    <div className="workflow-verdict"><strong>{verdictLabel}</strong>{job.metrics?.reason && <span>{job.metrics.reason}</span>}<small>执行退出码与业务结果分别记录；判定来自外部入口。</small></div>
    {job.metrics?.metrics?.length ? <div className="table-scroll"><table className="evidence-table"><thead><tr><th>指标</th><th>值</th><th>单位</th><th>来源 / 标签</th><th>样例 / 阈值 / 判定</th></tr></thead><tbody>{job.metrics.metrics.map((metric, index) => <tr key={index}><td>{metric.label || metric.name || '未命名指标'}</td><td>{text(metric.value)}</td><td>{metric.unit || '未提供'}</td><td>{text(metric.source)}{metric.tags && <small className="subline">{text(metric.tags)}</small>}</td><td>{text(metric.samples)} / {text(metric.threshold)} / {metric.verdict || '未提供'}</td></tr>)}</tbody></table></div> : null}
    {job.artifacts?.length ? <section><h4>原始产物</h4>{job.artifacts.map(artifact => <div className="workflow-artifact" key={artifact.id}><a href={artifact.download_url?.startsWith(base + '/artifacts/') ? artifact.download_url : `${base}/artifacts/${encodeURIComponent(artifact.id)}`} download aria-label={`下载产物 ${artifact.label}`}>{artifact.label || artifact.path}</a><span>{artifact.kind} · {artifact.size} B</span><code>{artifact.path}</code><small className="subline">SHA256 {artifact.sha256}</small></div>)}</section> : <p className="muted small">未提供可下载产物。</p>}
    {job.logs?.length ? job.logs.map((log, index) => <div className="log-panel" key={index}><div><span>{job.id} / {log.phase}</span><a href={`${base}/logs/${encodeURIComponent(log.phase)}`} download aria-label={`下载完整日志 ${log.phase}`}>下载完整日志</a></div>{(log.display_truncated || log.log_truncated) && <p className="notice compact">页面仅显示日志片段，请下载完整日志。</p>}<pre tabIndex={0} aria-label={`${job.id} ${log.phase} 日志`}>{log.text || '等待日志输出…'}</pre></div>) : <p className="muted small">尚无日志；不能据此判断执行成功。</p>}
  </div>;
}
