import type { WorkflowEnvironment, WorkflowJob } from '../workflowTypes';
import { artifactTargets, environmentTargets } from '../workflowArtifacts';
import { Field } from './ui';
import { WorkflowFiles } from './WorkflowFiles';

export function WorkflowJobEditor({ job, environments, onChange, onDelete, onReading }: { job: WorkflowJob; jobs: WorkflowJob[]; environments: WorkflowEnvironment[]; onChange: (value: Partial<WorkflowJob>) => void; onDelete: () => void; onReading: (delta: number) => void }) {

  return <section className="workflow-job" id={`editor-${job.id}`}><div className="workflow-job-row"><Field label={`${job.id} · 名称`}><input required maxLength={128} value={job.name} onChange={event => onChange({ name: event.target.value })} /></Field><div className="field"><span>目标环境</span><div className="choice-buttons" role="group" aria-label={`${job.id} · 目标环境`}>{environments.map(env => <button type="button" key={env.alias} aria-pressed={job.environment === env.alias} onClick={() => onChange({ environment: env.alias, node_aliases: undefined, artifacts: job.artifacts?.map(item => ({ ...item, targets: undefined, environment: undefined })) })}>{env.alias}</button>)}</div></div><Field label="NPU卡数"><input aria-label={`${job.id} · NPU 数量`} type="number" min={0} max={128} required value={job.npu_count} onChange={event => onChange({ npu_count: Number(event.target.value) })} /></Field><Field label="超时/分钟"><input aria-label={`${job.id} · 超时（分钟）`} type="number" min={1} max={10080} required value={job.timeout_seconds / 60} onChange={event => onChange({ timeout_seconds: Number(event.target.value) * 60 })} /></Field><button type="button" className="job-delete-button" aria-label={`删除作业 ${job.id}`} onClick={onDelete}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7" /></svg>删除作业</button></div><div className="choice-buttons job-kind" role="group" aria-label={`${job.id} · 执行方式`}><button type="button" aria-pressed={job.kind === 'batch'} onClick={() => onChange(job.kind === 'service' ? { kind: 'batch', post: [...job.ready, ...job.post], ready: [] } : { kind: 'batch' })}>运行后结束</button><button type="button" aria-pressed={job.kind === 'service'} onClick={() => onChange(job.kind === 'batch' ? { kind: 'service', ready: job.post, post: [] } : { kind: 'service' })}>常驻服务</button></div>
    <WorkflowFiles label={`${job.id} 前置校验`} steps={job.pre} onChange={pre => onChange({ pre })} onReading={onReading} />
    <WorkflowFiles label={`${job.id} 执行`} steps={job.steps} onChange={steps => onChange({ steps })} onReading={onReading} />
    <section className="workflow-followup"><WorkflowFiles label={`${job.id} 后续检查`} steps={job.kind === 'service' ? job.ready : job.post} onChange={steps => onChange(job.kind === 'service' ? { ready: steps } : { post: steps })} onReading={onReading} />
    <p className="muted small">{job.kind === 'service' ? '服务启动后检查，通过后执行下游作业。' : '执行结束后检查，失败则作业失败。'}</p>
    {job.kind === 'service' && job.post.length > 0 && <details><summary>已有的服务停止后检查</summary><WorkflowFiles label={`${job.id} 停止后检查`} steps={job.post} onChange={post => onChange({ post })} onReading={onReading} /></details>}
    {job.post.length > 0 && <div className="choice-buttons" role="group" aria-label={`${job.id} · 后续检查策略`}><button type="button" aria-pressed={job.post_policy === 'success'} onClick={() => onChange({ post_policy: 'success' })}>成功执行后检查</button><button type="button" aria-pressed={job.post_policy === 'always'} onClick={() => onChange({ post_policy: 'always' })}>始终检查</button></div>}</section>
    <section className="workflow-artifact-inputs"><div className="workflow-row-heading"><h3>产物归档</h3><button type="button" className="text-button" onClick={() => onChange({ artifacts: [...(job.artifacts || []), { path: '$HIVE_OUTPUT_DIR/result.json', label: '' }] })}>添加 {job.id} 产物</button></div><p className="muted small">文件或目录均可归档；默认使用当前作业的 $HIVE_OUTPUT_DIR。</p>{job.artifacts?.map((artifact, index) => <div className="workflow-artifact-row" key={index}><div className="field"><span>服务器 - 容器（多选）</span><details className="artifact-target-picker"><summary><span>选择产物服务器与容器</span></summary><div className="artifact-target-options" role="group" aria-label={`${job.id} 产物 ${index + 1} · 目标容器与节点`}>{environmentTargets(environments).map(target => { const selected = artifactTargets(artifact, job, environments); const included = selected.some(item => item.environment === target.environment && item.node_alias === target.node_alias); return <label key={target.environment + '/' + target.node_alias}><input type="checkbox" checked={included} onChange={() => onChange({ artifacts: job.artifacts!.map((item, i) => i === index ? { ...item, environment: undefined, targets: included ? selected.filter(value => value.environment !== target.environment || value.node_alias !== target.node_alias) : [...selected, target] } : item) })} />{target.node_alias} - {target.environment}</label>; })}<button type="button" className="text-button" onClick={() => onChange({ artifacts: job.artifacts!.map((item,i) => i === index ? {...item,targets:undefined,environment:undefined} : item) })}>恢复当前作业全部节点</button></div></details><small>{artifactTargets(artifact, job, environments).map(target => `${target.node_alias} - ${target.environment}`).join('，') || '尚未选择目标'}</small></div><Field label={`${job.id} 产物 ${index + 1} · 名称`}><input required value={artifact.label} onChange={event => onChange({ artifacts: job.artifacts!.map((item, i) => i === index ? { ...item, label: event.target.value } : item) })} /></Field><Field label={`${job.id} 产物 ${index + 1} · 路径`}><input aria-label={`${job.id} 产物 ${index + 1} · 路径`} required pattern={'(?:/.*|\\$HIVE_OUTPUT_DIR(?:/.*)?|\\$\\{HIVE_OUTPUT_DIR\\}(?:/.*)?)'} value={artifact.path} placeholder="$HIVE_OUTPUT_DIR/result.json" onChange={event => onChange({ artifacts: job.artifacts!.map((item, i) => i === index ? { ...item, path: event.target.value } : item) })} /></Field><button type="button" className="text-button" onClick={() => onChange({ artifacts: job.artifacts!.filter((_, i) => i !== index) })}>删除</button></div>)}</section>
  </section>;
}
