import type { WorkflowEnvironment } from '../workflowTypes';
import { Field } from './ui';
import { JsonField, WorkflowFiles } from './WorkflowFiles';

export function WorkflowEnvironmentEditor({ value: env, nodes, onChange, onReading, onDelete }: { value: WorkflowEnvironment; nodes: string[]; onChange: (value: Partial<WorkflowEnvironment>) => void; onReading: (delta: number) => void; onDelete: () => void }) {
  return <section className="workflow-environment"><div className="workflow-row-heading"><h4>{env.alias} <span className="tag">{env.role}</span></h4><button type="button" className="text-button danger-text" onClick={onDelete}>删除环境</button></div><div className="form-grid"><Field label={`${env.alias} · 节点代称`}><select value={env.node_alias} onChange={e => onChange({ node_alias: e.target.value })}>{!nodes.includes(env.node_alias) && <option value={env.node_alias}>{env.node_alias}（已移除，请重新选择）</option>}{nodes.map(node => <option key={node}>{node}</option>)}</select></Field><Field label={`${env.alias} · 镜像`}><input required value={env.image} onChange={e => onChange({ image: e.target.value })} placeholder="镜像名称与固定标签" /></Field></div>
    <details className="workflow-env-details"><summary>{env.alias} · 环境配置</summary><div className="form-grid"><Field label={`${env.alias} · 环境代称`}><input required pattern="[a-z][a-z0-9_]{0,31}" value={env.alias} onChange={event => onChange({ alias: event.target.value })} /></Field><Field label={`${env.alias} · 角色`}><select value={env.role} onChange={event => onChange({ role: event.target.value as 'server' | 'client' })}><option value="server">server</option><option value="client">client</option></select></Field><Field label={`${env.alias} · Shell 解释器`}><input required value={env.shell} onChange={event => onChange({ shell: event.target.value })} /></Field><Field label={`${env.alias} · Python 解释器`}><input required value={env.python} onChange={event => onChange({ python: event.target.value })} /></Field><Field label={`${env.alias} · 工作目录`}><input required value={env.workdir} onChange={event => onChange({ workdir: event.target.value })} /></Field></div>
    <JsonField label={`${env.alias} · 环境变量（JSON 对象）`} kind="object" value={env.environment} onChange={value => onChange({ environment: value as Record<string, string> })} />
    <h5>依赖输入</h5><p className="muted small">版本与安装来源作为参数传给 PR 安装入口，平台不生成安装命令。</p>{env.packages.map((pkg, index) => <div className="workflow-package" key={index}><Field label={`${env.alias} 依赖 ${index + 1} · 名称`}><input required value={pkg.name} onChange={event => onChange({ packages: env.packages.map((item, i) => i === index ? { ...item, name: event.target.value } : item) })} /></Field><Field label={`${env.alias} 依赖 ${index + 1} · 版本`}><input required value={pkg.version} onChange={event => onChange({ packages: env.packages.map((item, i) => i === index ? { ...item, version: event.target.value } : item) })} /></Field><Field label={`${env.alias} 依赖 ${index + 1} · 来源`}><input required value={pkg.source} onChange={event => onChange({ packages: env.packages.map((item, i) => i === index ? { ...item, source: event.target.value } : item) })} /></Field><button type="button" className="text-button" onClick={() => onChange({ packages: env.packages.filter((_, i) => i !== index) })}>删除依赖</button></div>)}<button type="button" className="text-button" onClick={() => onChange({ packages: [...env.packages, { name: '', version: '', source: '' }] })}>添加 {env.alias} 依赖</button>
    <h5>外部容器引导入口</h5><code className="subline">{env.bootstrap.path}</code><small className="muted">在绑定宿主机执行；内容摘要由中心核验。</small><WorkflowFiles label={`${env.alias} 安装`} steps={env.install} onChange={install => onChange({ install })} onReading={onReading} /><WorkflowFiles label={`${env.alias} 核验`} steps={env.verify} onChange={verify => onChange({ verify })} onReading={onReading} />
    </details></section>;
}
