import type { WorkflowEnvironment } from '../workflowTypes';
import { Field } from './ui';
import { WorkflowImagePicker } from './WorkflowImagePicker';
import { WorkflowFiles } from './WorkflowFiles';

export function WorkflowEnvironmentEditor({ value: env, nodes, onChange, onReading, onDelete }: { value: WorkflowEnvironment; nodes: string[]; onChange: (value: Partial<WorkflowEnvironment>) => void; onReading: (delta: number) => void; onDelete: () => void }) {
  const selected = env.node_aliases || [env.node_alias];
  return <section className="workflow-environment"><div className="workflow-row-heading"><h4>{env.alias}</h4><button type="button" className="text-button danger-text" onClick={onDelete}>删除环境</button></div><div className="workflow-environment-row"><Field label={`${env.alias} · 容器代称`}><input required pattern="[a-z][a-z0-9_]{0,31}" value={env.alias} onChange={event => onChange({ alias: event.target.value })} /></Field><div className="field"><span>服务器</span><div className="choice-buttons" role="group" aria-label={`${env.alias} · 服务器`}>{nodes.map(node => <button type="button" key={node} aria-pressed={selected.includes(node)} onClick={() => { const next = selected.includes(node) ? selected.filter(item => item !== node) : [...selected, node]; onChange({ node_aliases: next, node_alias: next[0] || '' }); }}>{node}</button>)}</div></div><WorkflowImagePicker label={`${env.alias} · 镜像`} value={env.image} onChange={image => onChange({image})} /></div><details className="workflow-bootstrap"><summary>创建容器（宿主机）</summary><p className="muted small">此步骤在所选服务器的宿主机上运行，用于创建当前环境的容器。</p><WorkflowFiles label={`${env.alias} 创建容器`} single steps={[env.bootstrap]} onChange={steps => { if (steps[0]) onChange({bootstrap: steps[0]}); }} onReading={onReading} /></details><WorkflowFiles label={`${env.alias} 安装`} steps={env.install} onChange={install => onChange({ install })} onReading={onReading} /><WorkflowFiles label={`${env.alias} 核验`} steps={env.verify} onChange={verify => onChange({ verify })} onReading={onReading} /></section>;
}
