ALTER TABLE users
 ADD COLUMN can_request BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN can_view_credentials BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN deleted_at DATETIME(6) NULL;
ALTER TABLE sessions ADD COLUMN admin_authenticated BOOLEAN NOT NULL DEFAULT FALSE;
