import type { ID, ResourceSpec } from './types';

export interface WorkflowSource { pr: number | string; head_sha: string; vllm_sha: string; repository?: string; url?: string }
export interface WorkflowInput { type: 'yaml'; path: string; uploaded_content?: string }
export interface WorkflowStep { launch?: string; files?: { name: string; content: string }[]; type: 'shell' | 'python' | 'yaml'; path: string; args: string[]; uploaded_content?: string; inputs?: WorkflowInput[]; runner?: { type: 'shell' | 'python'; path: string; args: string[] }; external?: boolean }
export interface WorkflowEnvironment { alias: string; role: 'server' | 'client'; node_alias: string; image: string; shell: string; python: string; workdir: string; environment: Record<string, string>; packages: { name: string; version: string; source: string }[]; bootstrap: WorkflowStep; install: WorkflowStep[]; verify: WorkflowStep[] }
export interface WorkflowDependency { job_id: string; condition: 'succeeded' | 'ready' }
export interface WorkflowArtifactSpec { environment?: string; path: string; label: string; kind?: 'file' | 'metrics' | 'auto' }
export interface WorkflowMetric { name?: string; label?: string; value?: unknown; unit?: string; source?: unknown; tags?: Record<string, unknown>; samples?: number; threshold?: unknown; verdict?: string }
export interface WorkflowLog { phase: string; text: string; display_truncated?: boolean; log_truncated?: boolean }
export interface WorkflowJob { id: string; name: string; environment: string; kind: 'batch' | 'service'; npu_count: number; ports: number[]; depends_on: WorkflowDependency[]; pre: WorkflowStep[]; steps: WorkflowStep[]; post: WorkflowStep[]; post_policy: 'success' | 'always'; ready: WorkflowStep[]; timeout_seconds: number; artifacts?: WorkflowArtifactSpec[] }
export interface WorkflowSpec { name: string; source: WorkflowSource; resource?: ResourceSpec; space_id?: ID; retain_minutes: number; environments: WorkflowEnvironment[]; jobs: WorkflowJob[] }
export interface WorkflowRun { id: ID; name: string; status: string; reason?: string; owner_name?: string; spec: WorkflowSpec; space_id: ID; created_at: string; started_at?: string; finished_at?: string; jobs: { id: string; name: string; status: string; phase?: string; reason?: string; logs?: WorkflowLog[]; exit_code?: number; endpoint?: string; cards?: string[]; attempts?: { phase: string; status: string; exit_code?: number; log_truncated?: boolean }[]; artifacts?: { id: string; environment?: string; label: string; path: string; kind: string; size: number; sha256: string; download_url: string }[]; metrics?: { metrics: WorkflowMetric[]; verdict: string; reason?: string } }[] }
export interface WorkflowSpace { id: ID; status: string; owner_name: string; retain_until?: string; spec: Partial<WorkflowSpec>; environments: (Partial<WorkflowEnvironment> & { alias: string; role: string; node_alias: string; status: string; container_name?: string; reason?: string; host?: string; node_id?: ID; logical_ids?: string[]; boot_id?: string; logs?: WorkflowLog[]; requested_packages?: { name: string; version: string; source: string }[]; identity?: Record<string, unknown> })[] }
export interface WorkflowPreset { id: ID; name: string; enabled: boolean; reason?: string; tags: Record<string, string | string[]>; source?: WorkflowSource; workflow?: Partial<WorkflowSpec> }
